// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// LeapYearHandlerFunc turns a function with the right signature into a leap year handler
type LeapYearHandlerFunc func(LeapYearParams) middleware.Responder

// Handle executing the request and returning a response
func (fn LeapYearHandlerFunc) Handle(params LeapYearParams) middleware.Responder {
	return fn(params)
}

// LeapYearHandler interface for that can handle valid leap year params
type LeapYearHandler interface {
	Handle(LeapYearParams) middleware.Responder
}

// NewLeapYear creates a new http.Handler for the leap year operation
func NewLeapYear(ctx *middleware.Context, handler LeapYearHandler) *LeapYear {
	return &LeapYear{Context: ctx, Handler: handler}
}

/* LeapYear swagger:route GET /isleap leapYear

Is given year leap or not

*/
type LeapYear struct {
	Context *middleware.Context
	Handler LeapYearHandler
}

func (o *LeapYear) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewLeapYearParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
