// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "Leap",
    "version": "0.0.1"
  },
  "basePath": "/api/v1",
  "paths": {
    "/isleap": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Is given year leap or not",
        "operationId": "leapYear",
        "parameters": [
          {
            "maximum": 9999,
            "minimum": -9999,
            "type": "integer",
            "description": "Year in range between -9999 to 9999, except 0",
            "name": "year",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Success"
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "Success": {
      "type": "object",
      "required": [
        "isLeap"
      ],
      "properties": {
        "isLeap": {
          "type": "boolean"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "Leap",
    "version": "0.0.1"
  },
  "basePath": "/api/v1",
  "paths": {
    "/isleap": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Is given year leap or not",
        "operationId": "leapYear",
        "parameters": [
          {
            "maximum": 9999,
            "minimum": -9999,
            "type": "integer",
            "description": "Year in range between -9999 to 9999, except 0",
            "name": "year",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Success"
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "Success": {
      "type": "object",
      "required": [
        "isLeap"
      ],
      "properties": {
        "isLeap": {
          "type": "boolean"
        }
      }
    }
  }
}`))
}
