swagger: "2.0"
info:
  title: "Leap"
  version: "0.0.1"
basePath: "/api/v1"

paths:
  /isleap:
    get:
      summary: "Is given year leap or not"
      operationId: "leapYear"
      parameters:
        - in: query
          name: year
          type: integer
          required: true
          description: "Year"
          minimum: -9999
          maximum: 9999
      produces:
        - application/json
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/Success"
        "400":
          description: "bad request"
          schema:
            $ref: '#/definitions/Error'
        "500":
          description: "internal server error"
          schema:
            $ref: '#/definitions/Error'


definitions:
  Success:
    type: object
    required:
      - isLeap
    properties:
      isLeap:
        type: boolean

  Error:
    type: object
    properties:
      message:
        type: "string"
